name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Check for secrets leak on the repo
      run: |
          git clone https://github.com/awslabs/git-secrets.git target
          cd target
          ./install.ps1
          echo "Git-secrets installation completed"
          git secrets --register-aws --global
          echo "Added aws secret templates"
          git secrets --scan -r ../
          echo "Repository scan completed"
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Setup .NET Core 5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.301
    - name: Install dependencies
      run: dotnet restore RecommendationTools/RecommendationValidator/RecommendationValidator.csproj
    - name: Validate
      run: for FILE in ./recommendation/*.recommendation.json ; do dotnet run --project RecommendationTools/RecommendationValidator/RecommendationValidator.csproj --path $FILE; done
